USE album_ratings;

INSERT INTO artists(artist_name) VALUES
('30H!3'),
('Ada'),
('Against Me!'),
('Alexisonfire'),
('Alice Et Moi'),
('Alice In Chains'),
('Alicia Keys'),
('All Time Low'),
('Alphaville'),
('Aly & AJ'),
('Amy Macdonald'),
('Annie'),
('Assertion'),
('Awaken I Am'),
('Benito Kamelas'),
('BIA'),
('Blink-182'),
('Bloc Party'),
('Bomfunk MC’s'),
('Bon Jovi'),
('Boys World'),
('Breathe Carolina'),
('Bridget Mendler'),
('Britney Spears'),
('Brooke Hyland'),
('Bruno Mars'),
('Busted'),
('Carry The Crown'),
('CeeLo Green'),
('Cemetery Sun'),
('Charlie Simpson'),
('Charlie XCX'),
('Chris Bourne'),
('Chris Isaak'),
('Chris Rea'),
('Christine and the Queens'),
('Courtney Love'),
('cupcake'),
('Danielle Peck'),
('Daniel Merriweather'),
('Dave Grohl'),
('David Bowie'),
('David Gray'),
('A Day To Remember'),
('Dayglow'),
('Dead Pony'),
('Deaftones'),
('Dinosaur Jr.'),
('DJ Iglu & Hartly Dark'),
('Drake'),
('Dream State'),
('Ed Sheeran'),
('Emma Blackery'),
('Fall Out Boy'),
('Felony Steve'),
('Fightstar'),
('Fireboy DML'),
('The Flaming Lips'),
('Flunk'),
('Foo Fighters'),
('Four Star Mary'),
('Freezepop'),
('Funeral For Friend'),
('Future Boy'),
('Garbage'),
('Gente De Zona'),
('Girli'),
('Good Charlotte'),
('Greta Van Fleet'),
('Grimes'),
('grouptherapy.'),
('Harold Melvin & The Blue Notes'),
('Harry Styles'),
('Hayley Kiyoko'),
('The Hobosexuals'),
('Hole'),
('I DONT KNOW HOW BUT THEY FOUND ME'),
('Iglu & Hartly'),
('INK.'),
('Imagine Dragons'),
('Jack Harlow'),
('JAY-Z'),
('Linkin Park'),
('Jeff Buckley'),
('Jeffree Star'),
('Jimmy Eat World'),
('Jonas Brothers'),
('Kanye West'),
('Kate Pierson'),
('Katy Perry'),
('Ke$ha'),
('KIDS SEE GHOSTS'),
('Killswitch Engage'),
('Kim Petras'),
('KIRBY'),
('Kreayshawn'),
('Kumo 99'),
('Kyo'),
('Lil Nas X'),
('Lo-Ball'),
('Lock-In'),
('Louis Tomlinson'),
('Lucia'),
('Madge'),
('Marvin Gaye'),
('Mastodon'),
('Matt Willis'),
('Mayorkun'),
('Mazzy Star'),
('McBusted'),
('McFly'),
('Medwin Goodall'),
('Melanie Martinez'),
('Metro Boomin'),
('Metronomy'),
('Michael Jackson'),
('Miley Cyrus'),
('Mindless Self Indulgence'),
('My Chemical Romance'),
('Niall Horan'),
('Niño Mandarina'),
('Nirvana'),
('Nkosazana Daughter'),
('Noah Kahan'),
('Noir Désir'),
('The Notorious B.I.G'),
('October Drift'),
('The Offspring'),
('Olivia Rodrigo'),
('One Direction'),
('The Orwells'),
('P!nk'),
('P-Square'),
('Panic! At The Disco'),
('Paramore'),
('Parcels'),
('Peaches'),
('Peter Bjorn and John'),
('Phillip Phillips'),
('Planes Mistaken For Stars'),
('Poppy'),
('PRESIDENT'),
('Queens of the Stone Age'),
('Rachel Chinouriri'),
('Rê Adegas'),
('Rema'),
('Rizha'),
('Robert Finley'),
('Rubber Man'),
('Sally Shapiro'),
('She Wants Revenge'),
('Silk Sonic'),
('Sinach'),
('Single By Sunday'),
('Sipprell'),
('Sisqo'),
('Sivert Høyem'),
('Sleep Token'),
('Slipknot'),
('The Smashing Pumpkins'),
('Son Of Dork'),
('The Struts'),
('Studio Killers'),
('The Sugarcubes'),
('Sunny Day Real Estate'),
('Superheaven'),
('System Of A Down'),
('Taylor Hawkins'),
('Taylor Swift'),
('Them Crooked Vultures'),
('The Travis Waltons'),
('Turnstile'),
('Uh Huh Her'),
('The Veronicas'),
('Vitas'),
('Waterparks'),
('X Ambassadors'),
('The Yagas'),
('Yellowcard'),
('ZAYN');

